apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaler
  namespace: demo
spec:
  scaleTargetRef:
    name: worker
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      queueName: myqueue
      host: amqp://guest:guest@rabbitmq.demo.svc.cluster.local:5672/
      queueLength: "5"
